# version: '3'

networks:
  api-tests:
    driver: bridge

services:
  # Test Container for running tests locally
  local_tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - dockertest.env
    depends_on:
      pennsievedb:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=pennsievedb
    volumes:
      - $PWD:/go/src/github.com/pennsieve/datasets-service
    networks:
      - api-tests

  # Test Container for Jenkins
  ci-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    env_file:
      - dockertest.env
    depends_on:
      pennsievedb-ci:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=pennsievedb-ci
    volumes:
      - $PWD:/go/src/github.com/pennsieve/datasets-service
    networks:
      - api-tests

  pennsievedb:
    image: pennsieve/pennsievedb:V20221102133799-seed
    restart: always
    ports:
      - "5432:5432"
    networks:
      - api-tests
    healthcheck:
      test: [ "CMD", "pg_isready", "-q" ]

  pennsievedb-ci:
    image: pennsieve/pennsievedb:V20221102133799-seed
    restart: always
    networks:
      - api-tests
    healthcheck:
      test: [ "CMD", "pg_isready", "-q" ]
